version: '3.8'

services:
  urlshortgen:
    restart: always
    build: .
    command: sh -c "/wait && ./main"
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - env/db-app.env

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - env/db-postgres.env
    ports:
      - 5432:5432